### ISSUE TITLE
Can connect to renderer but nothing is shown there

### ISSUE THREAD

**Issue by starbrights** [m3sv/PlainUPnP#12]
As in the headline: I can open the app and it finds the renderer, but the screen at TV stays black.
I recorded a log with my mobile and send it to your email (as in play store mentioned). Please have a look. A short feedback would be nice. Thank you!

**Comment by m3sv** [comment]
Hey @starbrights, you're probably not using app anymore, but maybe you can check out the latest version and see if that's the case?

**Comment by starbrights** [comment]
ATM my enigma2 sat box isn't visible as rendering device. Not sure anymore how I did get this working ...

**Comment by starbrights** [comment]
Same as before. renderer is (sometimes) visible in app, but it will not display anything (in opposite to BubbleUPNP as for instance).

**Comment by m3sv** [comment]
@starbrights Thanks for the update. Sorry that there is no update on this one, I'll check the email again to take another look at the issue. 😞

**Comment by m3sv** [comment]
Might be that it just failed to build content list. 

Could you, please, check out https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2 and see if it fixes the issue? 

I'll close the issue, since it has been over a year. Feel free to reopen in case the issue is still there.

Thanks!
