### ISSUE TITLE
unobvious bottom settings

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#15]
The bottom settings panel is extremely hard to find. (Not only the first time.)
![image](https://user-images.githubusercontent.com/14617699/66766675-58567e00-eeb7-11e9-8c53-ad01b0ee58ba.png)
![image](https://user-images.githubusercontent.com/14617699/66766677-5a204180-eeb7-11e9-89a4-3b2a012665c8.png)

I'm for make it always visible.

**Comment by m3sv** [comment]
Good timing. I was planning redesign because of the same reason.

**Comment by m3sv** [comment]
@532910 A slight redesign is made and will be released with 2.0. Thanks!

**Comment by 532910** [comment]
On the one hand it's fixed, as it's significant less confused now.
On the other:
1. what is the reason to hide it?
2. overall desing is confusing, unintuitive and inconvenient. Sorry ):

For example, selecting this device on the left and Play locally on the right, 
a. trying to play music does nothing
b. trying to play video asks to open external player, while looks like it has embedded one:
![image](https://user-images.githubusercontent.com/14617699/85138765-076c0600-b24c-11ea-814d-3a2e88bc02bc.png)

**Comment by m3sv** [comment]
> what is the reason to hide it?

There's nothing to hide right now indeed, I will go into details below.

> overall desing is confusing, unintuitive and inconvenient. Sorry ):

I didn't give much thought to players design, it's just a bad copy of a generic player right now.
A lot of elements are missing: repeat/play list, etc. Lots of ideas, no time or energy to implement unfortunatelly.

> For example, selecting this device on the left and Play locally on the right

How would you like to improve it?

>a. trying to play music does nothing

This should ask to open a player. Can you try with VLC installed?

>b. trying to play video asks to open external player, while looks like it has embedded one:

Yep, ideally I want to also embed player into the app, so that you can play without any other software.

**Comment by 532910** [comment]
> A lot of elements are missing: repeat/play list, etc. Lots of ideas, no time or energy to implement unfortunatelly.

It doesn't matter. I'm about overall usage, not missing elements.


>> a. trying to play music does nothing

> This should ask to open a player. Can you try with VLC installed?

It doesn't.

> How would you like to improve it?
![image](https://user-images.githubusercontent.com/14617699/85540384-964b9a80-b61f-11ea-90c0-e05ec9f5bd48.png)

see https://github.com/zhanghai/MaterialFiles for folder navigation example.
