### ISSUE TITLE
No way to exit the app other than closing it via recent apps or force close

### ISSUE THREAD

**Issue by Pentaphon** [m3sv/PlainUPnP#17]
Hi, I love the functionality of the app so far but there's no way to close the app other than closing it via the recent apps or force closing it. Can you add an exit button to the app or allow us to close it by pressing the back button to get a confirmation and pressing ok on the confirmation to close it?

Thanks.

**Comment by m3sv** [comment]
It's actually a bug. Will fix asap.

**Comment by m3sv** [comment]
@Pentaphon Done, a new "Are you sure you want to exit?" dialog and persistent notification with "Shutdown" button are added. Will be released with 2.0. Thanks!

**Comment by Pentaphon** [comment]
> @Pentaphon Done, a new "Are you sure you want to exit?" dialog and persistent notification with "Shutdown" button are added. Will be released with 2.0. Thanks!

Thank you! I am looking forward to using 2.0
