### ISSUE TITLE
Add a browser!

### ISSUE THREAD

**Issue by You-App** [m3sv/PlainUPnP#20]
First of all, thanks !!!
Can you add a browser to the application?

**Comment by wifitvbox** [comment]
@You-App @You-App

**Comment by m3sv** [comment]
@You-App Hello! 
What do you mean by "browser"? Like a content browser or internet browser?

Thanks!

**Comment by m3sv** [comment]
@You-App Closing this one.

If you still want this feature added, please open with a comment explaining what exactly needs to be implemented. Thanks!
