### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#30]

**Comment by Pentaphon** [comment]
Can't wait to see what 2.0 is like.

**Comment by m3sv** [comment]
@Pentaphon Don't hold your breath, mate. It's mostly refinement of the current design to make it more user friendly. 😅

If you have any feature/suggestion requests regarding something(e.g. design) then I'm all ears. 

Thanks!

**Comment by Pentaphon** [comment]
That's fine. It was the main issue I had besides the inability to easily close the app and to have a way of doing a simple UPNP server with a notification stop button. I'll be sure to stress test 2.0 and tell you if I find any more issues.

**Comment by m3sv** [comment]
I'm going to release an update at evening today. Decided to change some
workflow and thumbnails will be disabled by default. It works fine if you
have a couple of images, but on a device with a lot of stuff server will
simply choke on the amount of content. I'm thinking of adding a "download
thumbnail" button on each item so that you can preview what's in there
before streaming. That way you won't put as much pressure on the server and
device won't die trying to load billion images.

**Comment by Pentaphon** [comment]
You may also want to disable viewing images by default. Most people seem to care about video anyway and don't care too much about viewing pictures on their TV and they will still be able to enable pictures in the settings.

**Comment by Pentaphon** [comment]
> I'm going to release an update at evening today. 

Did you run into any issues?

**Comment by m3sv** [comment]
Nope, just Google as usual.
It can take up to 7 days they say.

**Comment by Pentaphon** [comment]
> Nope, just Google as usual. It can take up to 7 days they say.

Oh I was looking for it on your github releases page, which doesn't have anything. I see it on Google Play now! I will stress test it and report any issues on your issues page! Thanks very much for your work!
