### ISSUE TITLE
Feature Request: Show PlainUPNP's icon when it shows up on a UPNP client

### ISSUE THREAD

**Issue by Pentaphon** [m3sv/PlainUPnP#39]
Here's my Samsung HDTV showing the icons of the UPNP servers it can find on the network. 

On the right is Kodi, showing its app icon as expected.  

On the left is PlainUPNP, with no app icon, and the TV showing a generic icon in its place. 

Can we get an icon for PlainUPNP?

![IMG_20200331_154912](https://user-images.githubusercontent.com/49374058/78082663-6a927e80-7368-11ea-831a-dc960abb37ad.jpg)

**Comment by m3sv** [comment]
I don't have access to my TV at the moment. But it doesn't seem to be hard thing to do, seems like Cling(UPnP library that we use) issue.

Right now I'm busy with FDroid inclusion, once that is done I will create a priority list. 

Thanks. 👍

**Comment by m3sv** [comment]
Done. Should land in 2.1
