### ISSUE TITLE
No way to start/pause server@Eric Malmberg

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#4]
Add start/pause server entry to settings.

**Comment by Pentaphon** [comment]
@m3sv can you make it so a notification pops up when the server is started, and also put a "stop" button on the notification to make it easy to stop the server from anywhere on your phone without having to go to the app itself?

**Comment by m3sv** [comment]
Yes! It's one of the planned features. 
I really need to create a roadmap. 🙂

**Comment by m3sv** [comment]
#17
