### ISSUE TITLE
Using system's default music player

### ISSUE THREAD

**Issue by peeyushsrj** [m3sv/PlainUPnP#41]
I love the app. Except when it's asking me to open the music app from a list of music player. This step seems repetitive. It will be good to have a setting, where I can set my media to play with default VLC.
Would be super useful.

**Comment by m3sv** [comment]
Glad that you like it. 
This doesn't seem like a difficult thing to implement, I will add it in 2.1.

Thank you!

**Comment by m3sv** [comment]
Done. Will be released with 2.1.
