### ISSUE TITLE
Feature Request: show thumbnails in file list view

### ISSUE THREAD

**Issue by Pentaphon** [m3sv/PlainUPnP#47]
When browsing the videos on my phone, I notice there's only generic video icons when scrolling through lists of videos. Can we get thumbnails when scrolling through the file lists instead of showing the thumbnail only on the player controls? It would make picking a video much visually simpler than reading filenames. 

![Screenshot_20200422-065432](https://user-images.githubusercontent.com/49374058/79990968-8fa97700-8466-11ea-9ab4-629731208d6b.png)

**Comment by m3sv** [comment]
We had this feature before and depending on content and it's amount it may slow down device to a crawl. I need to think how to implement this in a more efficient way. 🤔

I might return it for now how it was before, make it opt-in and disabled by default. Or just make it like it was before with opt-out in settings.

**Comment by Pentaphon** [comment]
> I might return it for now how it was before, make it opt-in and disabled by default.

That would be ideal.

**Comment by m3sv** [comment]
@Pentaphon Live in 2.2.0. 👍
