### ISSUE TITLE
Feature Request: instead of showing "empty item" each time app is opened, just use the last selection used

### ISSUE THREAD

**Issue by Pentaphon** [m3sv/PlainUPnP#48]
It's a bit annoying to have to select these each time I open the app. Perhaps it can just stay on the last entries selected the previous time you used the app. That would save a lot of time, especially considering we mostly use your app on 1 television or device, maybe 2 at most. 

![Screenshot_20200422-063711](https://user-images.githubusercontent.com/49374058/79989180-6b4c9b00-8464-11ea-9dd3-8433756cb494.png)

**Comment by m3sv** [comment]
Done! Will be released with the next version. 

Some checks are still running, but it will land in develop soon.
https://github.com/m3sv/PlainUPnP/pull/69

I will close the issue just before release, feel free to reopen it if something is wrong with the implementation.
