### ISSUE TITLE
add a option to choose a default app to open the content [feature/enhanced request]

### ISSUE THREAD

**Issue by AndersonGI** [m3sv/PlainUPnP#58]
I am trying to watch some videos on my android, but instead of sending them to vlc or the default video system reproducer it is sending to my default browser to downloading.

**Comment by m3sv** [comment]
Will add with the next release, thanks!

**Comment by AndersonGI** [comment]
Thank you. I've tried many apps with this feature, many of them lack the ability to load the local subtitle alongside the video on the server folder, because of that I've downloaded vlc, take a good look on this.

**Comment by m3sv** [comment]
I'm not sure if it will have subtitles support, though. Need to investigate this further.

**Comment by m3sv** [comment]
Should be fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.

Feel free to reopen in case it is not.

As for the subtitles, please, open up a separate Issue.

Thanks!
