### ISSUE TITLE
my volume buttons are on the left

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#59]
![image](https://user-images.githubusercontent.com/14617699/85123110-4d1ad580-b230-11ea-97d6-543b93bea591.png)

**Comment by m3sv** [comment]
I knew someone would create such issue. I myself have Samsung with buttons on the left. 😂

This was the fastest solution to implement. But I feel like there's a strong need for a better onboarding flow, will work on this. 

Thanks!

**Comment by 532910** [comment]
What's about just add one more arrow or remove the current one?

Also I'd add the _side_ word: `Control volume with side buttons`

**Comment by m3sv** [comment]
Thanks for the suggestion, changed to "Control volume with side buttons". 

For now I will stick with the arrows, but PlainUPnP definitely needs better onboarding.
