### ISSUE TITLE
controls button issue in search mode

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#61]
![image](https://user-images.githubusercontent.com/14617699/85129614-121e9f00-b23c-11ea-9f38-f0f0ebe9ec30.png)

**Comment by m3sv** [comment]
Thanks, will be fixed with next release!

**Comment by m3sv** [comment]
Replaced with the "Search" button in overflow menu, so the issue should be gone.

**Comment by 532910** [comment]
ack
