### ISSUE TITLE
Empty item

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#62]
What are they for?
![image](https://user-images.githubusercontent.com/14617699/85129746-5316b380-b23c-11ea-9a0d-5635e12979d3.png)

**Comment by m3sv** [comment]
Just a placeholder for select nothing. I will replace empty item with blank space because it is indeed confusing now.

**Comment by 532910** [comment]
But what is the reason to select nothing?

**Comment by m3sv** [comment]
Something might get stuck, or you have a deep hierarchy of files and would rather start from home. 
Since you cannot select same item twice you need to select something else, or nothing

**Comment by 532910** [comment]
So it's a dirty workaround and should be completely removed!

**Comment by m3sv** [comment]
Fair enough. While looking into it I remembered why it was added, because Android Spinner gave me a looot of headache at the time. Now that we've migrated to Material dropdowns this is indeed obsolete. Will be removed in the next release.

Thanks!

**Comment by 532910** [comment]
ack
