### ISSUE TITLE
Contact us doesn't work

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#63]
Just nothing happens when I press it:
![image](https://user-images.githubusercontent.com/14617699/85131267-1ef0c200-b23f-11ea-8443-f83e54e237bb.png)

**Comment by m3sv** [comment]
Do you have email client installed? 🤔

I need to show descriptive errors when intents fail to resolve.

**Comment by 532910** [comment]
Yep, K9!

**Comment by 532910** [comment]
Moreover, I see nothing interesting in logcat.

**Comment by m3sv** [comment]
Fixed intent, hopefully it will work this time. Tried installing K9, but for some it doesn't recognise "mailto:" links. I've added a fallback in case it doesn't work, so that you can still copy an email to clipboard.

**Comment by 532910** [comment]
But K9 works fine for all other apps that I know. Not sure if a fallback for coping link to clipboard is a good idea.

**Comment by m3sv** [comment]
Please try the latest version(will release today), if it still doesn't work I will investigate further.

**Comment by m3sv** [comment]
Will close this for now. Feel free to reopen if the issue still persists.

**Comment by 532910** [comment]
I confirm it's fixed.
