### ISSUE TITLE
Default theme: Not set

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#73]
It shows `Not set` but should be `System-based`:

![image](https://user-images.githubusercontent.com/14617699/86101113-7524f700-bac2-11ea-8c11-bdd10e60339e.png)

**Comment by m3sv** [comment]
Default mode follows System. 😉

It is because flag is empty it shows not set. Will take a look if I can make it set by default.

**Comment by 532910** [comment]
> Default mode follows System

Yes, this works fine!

The issue is that `Not set` should never be shown.

**Comment by m3sv** [comment]
Thank you! Closing this now, lands with 2.6.2.

**Comment by 532910** [comment]
Looks fine now, thank you!
