### ISSUE TITLE
Howto Stop playback?

### ISSUE THREAD

**Issue by gjaekel** [m3sv/PlainUPnP#81]
I just evaluate PlainUPnP, it seems to serve exactly me needs.

As a test case, I use it to browse my DLNA media server (minidlna, at my local home server) and my DLNA audio renderer (also on this server). 

This works well, but I can't figure out how to "stop", i.e. shutdown the playback of the current title. Using the Pause/Play-icon, i'm able to interrupt and restart the playback. But how to stop listening or switch to another title, please?

I hope it's not to obvious and I get a face-palm ...

**Comment by m3sv** [comment]
> I hope it's not to obvious and I get a face-palm ...

Nope. Was just a shitty UX, unfortunately. 

In https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2 you can press the `x` icon and it will send `stop` command to your server.

Will be closing this, feel free to reopen in case this is not enough. I might think about adding dedicated button for this...
