### ISSUE TITLE
feature: play items in folder

### ISSUE THREAD

**Issue by f1-outsourcing** [m3sv/PlainUPnP#87]
Would be nice to play (all) items in a folder, or multi select items to be played.

Thanks again!

**Comment by m3sv** [comment]
Should be fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.

Feel free to reopen in case it's no working as expected. 🙂

**Comment by f1-outsourcing** [comment]
Hi I just installed the new release. Sorry for asking such simple question, but how do I play all items in a folder/playlist? I tried long pressing but I am only able to play just one track.

my source is a dlna server and play destination is a remote tv.

**Comment by arbitrary-dev** [comment]
I'm having 3.0.2 on Android and there's no play all items in folder neither in **Player mode** nor in **Streaming**.
